django_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from jokerank import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    # our apps
    url(r'^', include('stats.urls', namespace='stats')),
    url(r'^jokes/', include('jokerank.urls', namespace='jokerank')),

    url(r'^profile/$', views.user_profile, name='user_profile'),

    # signup/login/logout
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', auth_views.login, {'template_name': 'jokerank/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
]

jokerank/urls.py
from django.conf.urls import include, url

from . import views

app_name = 'jokerank'
urlpatterns = [
    url(r'^$', views.show_jokes, name='show_jokes'),
    url(r'^add/$', views.add_joke, name='add_joke'),
    url(r'^details/(?P<joke_id>[0-9]+)/$', views.joke_details, name='joke_details'),
]

stats/urls.py
from django.conf.urls import url

from . import views

app_name = 'stats'
urlpatterns = [
    url(r'^$', views.show_stats, name='show_stats'),
    url(r'^rating/update/$', views.update_rating, name='update_rating'),

]

jokerank/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

from api.models import JokeRater

class User(AbstractUser):
    '''
    Subclassed django user model (inherits username, password, etc.)
    Has an optional one-to-one relationship with a joke rater/submitter.
    '''

    joke_rater = models.OneToOneField(JokeRater, null=True, blank=True)

    def __unicode__(self):
        return self.username

jokerank/forms.py
from iso3166 import countries

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.conf import settings
from django.contrib.auth import get_user_model

from api.models import JokeRating, Joke, JokeRater, JOKE_CATEGORIES, JOKE_TYPES
User = get_user_model()


class SignUpForm(UserCreationForm):
    ''' 
    Form for registering an account. 
    Only asks user for username, password, and password confirmation.
    Optionally allows them to link with their joke ratings they made.
    '''
    joke_submitter_id = forms.CharField(required=False, max_length=settings.CHAR_FIELD_MAX_LENGTH)

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        ''' 
        Initialize the widgets of the form (add the Bootstrap class form-control, placeholders).
        '''
        super(SignUpForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs = {
            'placeholder': 'Username',
            'class': 'form-control'
        }
        self.fields['password1'].widget.attrs = {
            'placeholder': 'Password',
            'class': 'form-control'
        }
        self.fields['password2'].widget.attrs = {
            'placeholder': 'Password Again',
            'class': 'form-control'
        }
        self.fields['joke_submitter_id'].widget.attrs = {
            'placeholder': 'Joke Submitter ID (optional)',
            'class': 'form-control'
        }

    def save(self, commit=True):
        '''
        On saving the model form, attempt to create a relationship between a JokeRater and
        this user (if they want to).
        '''
        errors = []
        user = super(SignUpForm, self).save(commit=False)
        jsmid = self.cleaned_data.get('joke_submitter_id')
        if jsmid:
            try:
                joke_rater = JokeRater.objects.get(
                    joke_submitter_id=self.cleaned_data.get('joke_submitter_id'))
            except JokeRater.DoesNotExist: # no joke rater in DB with that ID
                joke_rater = JokeRater.objects.create(joke_submitter_id=jsmid)
                errors.append('There was no Joke Rater with ID={0}. We created one for you.'.format(jsmid))
            except JokeRater.MultipleObjectsReturned: # multiple joke raters with that ID
                errors.append('Database Corruption. There were multiple JokeRaters with the same ID={0}.'.format(jsmid))
                errors.append('Creating a new joke rater for you to use.')
                joke_rater = JokeRater.objects.create()

            # already associated with someone
            if hasattr(joke_rater, 'user'):
                errors.append('That joke submitter id is already associated with a user. We created a new one for you.')
                joke_rater = JokeRater.objects.create()
        else:
            joke_rater = JokeRater.objects.create()
            
        user.joke_rater = joke_rater

        if commit:
            user.save()
        return user, errors


class CreateJokeForm(forms.ModelForm):
    ''' 
    A form for creating a joke.
    joke_source, joke_submitter automatically populated by user who created joke.
    '''
    class Meta:
        model = Joke
        fields = ('joke_text', 'category', 'joke_type', 'subject')
        widgets = {
            'category': forms.Select(choices=JOKE_CATEGORIES),
            'joke_type': forms.Select(choices=JOKE_TYPES)
        }

    def __init__(self, *args, **kwargs):
        ''' 
        Initialize the widgets of the form (add the Bootstrap class form-control, placeholders).
        '''
        super(CreateJokeForm, self).__init__(*args, **kwargs)
        self.fields['joke_text'].widget.attrs = {
            'placeholder': 'The joke itself.',
            'class': 'form-control'
        }
        self.fields['category'].widget.attrs = {
            'class': 'form-control'
        }
        self.fields['joke_type'].widget.attrs = {
            'class': 'form-control'
        }
        self.fields['subject'].widget.attrs = {
            'placeholder': 'Joke Subject (e.g. Donald Trump)',
            'class': 'form-control'
        }

    def save(self, joke_submitter, commit=True):
        '''
        On saving the model form, auto fill the joke_source and joke_submitter.
        '''
        joke = super(CreateJokeForm, self).save(commit=False)
        joke.joke_source = 'website'
        joke.joke_submitter = joke_submitter
        if commit:
            joke.save()
        return joke


AGES = tuple([(i, i) for i in range(1, 100)])
GENDER = (
    ('Female', 'Female'),
    ('Male', 'Male'),
    ('Prefer not to say', 'Prefer not to say'),
)
COUNTRIES = tuple([(c.name, c.name) for c in countries])
MAJOR = (
    ('Computer Science/CSE', 'Computer Science/CSE'),
    ('Physics', 'Physics'),
    ('Math', 'Math'),
    ('Computer Engineering', 'Computer Engineering'),
    ('Electrical Engineering', 'Electrical Engineering'),
    ('Mechanical Engineering', 'Mechanical Engineering'),
    ('Biochemical Engineering', 'Biochemical Engineering'),
    ('Other', 'Other')
)
MUSIC = (
    ('Rock', 'Rock'),
    ('Hip-Hop', 'Hip-Hop'),
    ('Rap', 'Rap'),
    ('Metal', 'Metal'),
    ('Pop', 'Pop'),
    ('Jazz', 'Jazz'),
    ('Blues', 'Blues'),
    ('Country', 'Country'),
    ('Alternative Rock', 'Alternative Rock'),
    ('Indie', 'Indie'),
    ('Reggae', 'Reggae'),
    ('Classical', 'Classical'),
    ('EDM', 'EDM')
)
MOVIES = (
    ('Thriller', 'Thriller'),
    ('Horror', 'Horror'),
    ('Action', 'Action'),
    ('Superhero', 'Superhero'),
    ('Mystery', 'Mystery'),
    ('Comedy', 'Comedy'),
    ('Romantic comedy', 'Romantic comedy'),
    ('SciFi', 'SciFi'),
    ('Documentary', 'Documentary'),
    ('Indie', 'Indie'),
    ('Family', 'Family')
)

class EditJokeRaterForm(forms.ModelForm):
    '''
    Form for editing your user account after it is created.
    '''
    class Meta:
        model = JokeRater
        exclude = ('joke_submitter_id', 'id')
        widgets = {
            'age': forms.Select(choices=AGES),
            'gender': forms.Select(choices=GENDER),
            'birth_country': forms.Select(choices=COUNTRIES),
            'major': forms.Select(choices=MAJOR),
            'preferred_joke_genre': forms.Select(choices=JOKE_CATEGORIES),
            'preferred_joke_genre2': forms.Select(choices=JOKE_CATEGORIES),
            'preferred_joke_type': forms.Select(choices=JOKE_TYPES),
            'favorite_music_genre': forms.Select(choices=MUSIC),
            'favorite_movie_genre': forms.Select(choices=MOVIES),
        }

    def __init__(self, *args, **kwargs):
        ''' 
        Initialize the widgets of the form (add the Bootstrap class form-control, placeholders).
        '''
        super(EditJokeRaterForm, self).__init__(*args, **kwargs)
        self.fields['gender'].widget.attrs = {
            'class': 'form-control'
        }
        self.fields['age'].widget.attrs = {
            'class': 'form-control',
        }
        self.fields['birth_country'].widget.attrs = {
            'class': 'form-control'
        }
        self.fields['major'].widget.attrs = {
            'class': 'form-control'
        }
        self.fields['preferred_joke_genre'].widget.attrs = {
            'class': 'form-control'
        }
        self.fields['preferred_joke_genre2'].widget.attrs = {
            'class': 'form-control'
        }
        self.fields['preferred_joke_type'].widget.attrs = {
            'class': 'form-control'
        }
        self.fields['favorite_music_genre'].widget.attrs = {
            'class': 'form-control'
        }
        self.fields['favorite_movie_genre'].widget.attrs = {
            'class': 'form-control'
        }

jokerank/views.py
from django.http import HttpResponse
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from django.views.decorators.cache import never_cache
from django.views.decorators.cache import cache_control
from django.contrib import messages
from django.db.models import Avg

from .forms import SignUpForm, CreateJokeForm, EditJokeRaterForm
from api.models import Joke, JokeRating


@login_required
@require_http_methods(['GET'])
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def show_jokes(request):
    ''' 
    Page that shows the list of jokes, allows users to click on them
    and see their fields, etc.
    '''
    # order jokes by their average rating
    jokes = Joke.objects.annotate(avg_rating=Avg('joke_ratings__rating')).order_by('-avg_rating')

    # efficiently rank the jokes instead of using ranking property (can do them all at once)
    prev_value = -1.0
    cur_ranking = 1
    num_repetitions = 1
    for joke in jokes:
        joke.cur_ranking = cur_ranking
        if joke.avg_rating == prev_value:
            num_repetitions += 1
        else:
            cur_ranking += num_repetitions
            num_repetitions = 1
            prev_value = joke.avg_rating

    return render(request, 'jokerank/jokes.html', {'jokes': jokes})


@login_required
@require_http_methods(['GET', 'POST'])
def add_joke(request):
    ''' 
    GET request means return the main add joke form page.
    POST request means try to create the joke they submitted, redirect if success.
    '''
    if request.method == 'GET':
        create_joke_form = CreateJokeForm()
        context = {
            'create_joke_form': create_joke_form
        }
        return render(request, 'jokerank/add-joke.html', context)
    else:
        create_joke_form = CreateJokeForm(request.POST)
        if create_joke_form.is_valid():
            create_joke_form.save(request.user.joke_rater)
            return redirect(reverse('jokerank:show_jokes'))
        else:
            context = {
                'create_joke_form': create_joke_form
            }
            return render(request, 'jokerank/add-joke.html', context)
        

@login_required
@require_http_methods(['GET'])
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def joke_details(request, joke_id):
    ''' 
    Render a page containing detials about the joke with ID=joke_id.
    Redirect to home page with error if joke ID is invalid somehow.
    '''
    try:
        joke = Joke.objects.get(id=joke_id)
        avg_rating = joke.average_rating
        rating_distribution = joke.get_rating_distribution()
    except Exception as e:
        print "Error @joke_details: {0}.".format(e)
        return redirect(reverse('jokerank:show_jokes'))
    context = {
        'joke': joke,
        'joke_dist_x': [1, 2, 3, 4, 5],
        'joke_dist_y': rating_distribution
    }
    return render(request, 'jokerank/joke.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def user_profile(request):
    ''' 
    GET: show the user profile with a form that they can use to change their features.
    POST: form has been submitted, check if it is valid, save changes.
    '''
    if request.method == 'GET':
        joke_rater = request.user.joke_rater
        joke_rater_form = EditJokeRaterForm(instance=joke_rater)
        context = {
            'joke_rater_form': joke_rater_form
        }
        return render(request, 'jokerank/user-profile.html', context)
    else:
        joke_rater = request.user.joke_rater
        joke_rater_form = EditJokeRaterForm(request.POST, instance=joke_rater)
        if joke_rater_form.is_valid():
            joke_rater_form.save()
            return redirect(reverse('stats:show_stats'))
        else:
            context = {
                'joke_rater_form': joke_rater_form
            }
            return render(request, 'jokerank/user-profile.html', context)



############################ AUTH VIEWS #################################


def signup(request):
    ''' 
    View for creating a username/password/info. 
    '''
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user, errors = form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            for message in errors:
                messages.info(request, message)
            return redirect(reverse('user_profile'))
        else:
            context = {
                'form': form
            }
            return render(request, 'jokerank/signup.html', {'form': form})
    else:
        form = SignUpForm()
    return render(request, 'jokerank/signup.html', {'form': form})


def logout_success(request):
    ''' 
    On logging out, user is redirected to this page. 
    '''
    return render(request, 'jokerank/logout-success.html')

jokerank/templates/jokerank/add-joke.html
{% extends 'jokerank/base.html' %}

{% block create-joke-nav %}class="active"{% endblock %}

{% block title %}Add Joke{% endblock %}

{% block content %}
<h2>Create a Joke</h2>
<hr>
<form id="create_joke_form" action="{% url 'jokerank:add_joke' %}" method="POST">
    {% for field in create_joke_form %}
    <div class="form-group">
        <label>{{ field.label|title }}</label>
        {{ field }}
    </div>
    {% endfor %}
    <button class="btn">Create</button>
    {% csrf_token %}
</form>
{% endblock %}

jokerank/templates/jokerank/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>{% block title %}ECS 171 Jokes{% endblock %}</title>
    <meta name="description" content="ECS 171 Jokes">

    {# boostrap css cdn #}
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" 
        rel="stylesheet" 
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" 
        crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


    {# TODO: figure out static files, put this in a file #}
    <style>
        body {
            /*background-color: beige;*/
        }

        .navbar-inverse {
            /*background-color: darkcyan;*/
        }

        .navbar-brand {
            font-size: 28px;
        }

        .navbar-nav {
            text-align:center;
        }

        .glyphicon {
            margin-right: 5px;
        }

        .checked {
            color: orange;
        }
    </style>

    {# to include your own styles (inline) override this block #}
    {% block styles %}{% endblock %}

    <!--[if lt IE 9]>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script>
    <![endif]-->
</head>

<body style="padding-bottom: 70px">

{# navbar #}
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <a href="{% url 'stats:show_stats' %}" class="navbar-brand">JokeDB</a>
        </div>
        <ul class="nav navbar-nav">
            <li {% block stat-nav %}{% endblock %}><a href="{% url 'stats:show_stats' %}">Statistics</a></li>
            <li {% block jokes-nav %}{% endblock %}><a href="{% url 'jokerank:show_jokes' %}">Jokes</a></li>
            <li {% block create-joke-nav %}{% endblock %}><a href="{% url 'jokerank:add_joke' %}">Create Joke</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
                <li {% block profile-nav %}{% endblock %}><a href="{% url 'user_profile' %}"><span class="glyphicon glyphicon-user"></span>{{ user.username }}</a></li>
                <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-out"></span>Logout</a></li>
            {% else %}
                <li {% block signup-nav %}{% endblock %}><a href="{% url 'signup' %}"><span class="glyphicon glyphicon-user"></span>Sign Up</a></li>
                <li {% block login-nav %}{% endblock %}><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
            {% endif %}
        </ul>
    </div>
</nav>

{# main content of page #}
<div id="content" class="container">
    {% block content %}{% endblock %}
</div>

<footer class="navbar navbar-default navbar-fixed-bottom text-center" style=" margin: 0 auto !important;right:0; bottom:0;left:0;padding: 1rem; background-color: #efefef;text-align:center !important;position:fixed">

    <h4>ECS 171 Joke Learning Project</h4>

</footer>


{# CDN's (jquery, bootstrap, plotly) #}
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
<script src="https://code.jquery.com/jquery-3.2.1.min.js"
    integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
    crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" 
    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" 
    crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>

{# to include your own scripts, override this block #}
{% block scripts %}{% endblock %}

</body>
</html>

jokerank/templates/jokerank/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  {% load static %}
  <link rel="stylesheet" type ="text/css" href="{% static 'jokerank/main.css' %}"/>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand">Joke DataBase</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>
      <li><a href="#">Statistics</a></li>
      <li><a href="#">Create Joke</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
  </div>
</nav>
    
</body>
</html>

jokerank/templates/jokerank/joke.html
{% extends 'jokerank/base.html' %}
{% load stats_extras %}

{% block jokes-nav %}class="active"{% endblock %}

{% block title %}Joke: {{ joke.id }}{% endblock %}

{% block content %}
<div id="{{ joke.id }}" class="panel panel-info">
	<div class="panel-heading">
		<h2 class="text-center panel-title" style="font-size: 30px">{{joke.joke_text }}</h2>
	</div>
	<div class="panel-body">
		<div class="row">
			<div class="col-lg-3" style="padding-top: 30px">
				<ul style="list-style-type: none;">
					<li><h2>Category: </h2><h4>{{ joke.category }}</h4></li>
					<li><h2>Subject: </h2><h4>{{ joke.subject }}</h4></li>
					<li><h2>Type: </h2><h4>{{ joke.joke_type }}</h4></li>
					<li><h2>Submitted By: </h2><h4>{{ joke.joke_submitter }}</h4></li>
                    <li><h2>Average Rating: </h2><h4 style="color: green;">
                        {% with curr_rating=joke.average_rating %}
                            {% if curr_rating == -1 %}
                                No ratings.
                            {% else %}
                                {{ joke.average_rating|floatformat:"4" }}
                            {% endif %}
                        {% endwith %}
                    </h4></li>
                    <li><h2>Ranking: </h2><h4>{{ joke.ranking }}</h4></li>
				</ul>
			</div>
			<div class="col-lg-9">
				<div id="joke_dist"></div>
			</div>
		</div>
	</div>
</div>

<div class="row">
    <div class="col-sm-3 col-sm-offset-9">
        <div id="{{ joke.id }}" class="panel panel-info" style="padding: 1em; text-align: center;">
        {% with user_rating=joke|user_joke_rating:user %}
            {% if user_rating == -1 %}
                No Associated Rater
            {% else %}
                Your rating: 
                {% for i in '_____' %}
                    <span class="fa fa-star star star{{ forloop.counter }} {% if forloop.counter <= user_rating %}checked {% endif %}"></span>
                {% endfor %}
            {% endif %}
        {% endwith %}
        </div>
    </div>
</div>
{# TODO: allow user to change their rating here #}
{% endblock %}

{% block scripts %}
<script type="text/javascript">

    $(document).ready(function() {
        var data = [
          {
            x: {{ joke_dist_x }},
            y: {{ joke_dist_y }},
            type: 'bar',
            name: 'Ratings'
          }
        ];
        var layout = {
        	title: "Joke Rating",

        };
        Plotly.newPlot('joke_dist', data, layout, {displayModeBar: false});

        window.onresize = function() {
        	var gd3 = Plotly.d3.select('#joke_dist');
        	var gd = gd3.node();

            Plotly.Plots.resize(gd);
        };
    });

    $(document).off('click', '.star').on('click', '.star', function(e) {
        var $panel = $(this).closest('.panel');
        var $spans = $panel.find('.star');
        var $clickedStar = $(this);
        $spans.removeClass('checked');
        var rating = 0;
        $spans.each(function() {
            var r = true;
            if ($clickedStar.is($(this))) {
                r = false; // break
            }
            $(this).addClass('checked');
            rating++;
            return r;
        });

        var url = "{% url 'stats:update_rating' %}";
        var post_data = {
            'rating': rating,
            'joke_id': $panel.attr('id'),
            'csrfmiddlewaretoken': '{{ csrf_token }}'
        }

        $.post(url, post_data, function(data) {
            console.log("success");
        });
    });
</script>
{% endblock %}

jokerank/templates/jokerank/jokes.html
{% extends 'jokerank/base.html' %}
{% load stats_extras %}

{% block jokes-nav %}class="active"{% endblock %}

{# override the title portion of base.html #}
{% block title %}All Jokes{% endblock %}

{# override the content portion of base.html #}
{% block content %}
{% if jokes %}
<h2>All Jokes</h2>
<div class="table-responsive">
	<table id="all_jokes_table" class="table table-bordered table-hover table-condensed table-striped">
		<thead>
			<tr>
				<th style="width: 74%;">Text</th>
				<th style="width: 12%">Rating (Click Me!)</th>
				<th style="width: 8%">Ranking</th>
				<th style="width: 8%">Avg. Rating</th>
				<th style="width: 12%;">Actions</th>
			</tr>
		</thead>
		<tbody>
			{% for joke in jokes %}
				<tr id="{{ joke.id }}">
					<td>{{ joke.joke_text }}</td>
					<td style="text-align: center; vertical-align: middle;">
						{% with user_rating=joke|user_joke_rating:user %}
							{% if user_rating == -1 %}
								No Associated Rater
							{% else %}
								{% for i in '_____' %}
									<span class="fa fa-star star star{{ forloop.counter }} {% if forloop.counter <= user_rating %}checked {% endif %}"></span>
								{% endfor %}
							{% endif %}
						{% endwith %}
					</td>
					<td>{{ joke.cur_ranking }}</td>
					<td>{{ joke.average_rating|floatformat:4 }}</td>
					<td>
						<a style="width: 100%;" class="btn btn-default btn-outline-info" href="{% url 'jokerank:joke_details' joke.id %}">Details</button>
					</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
</div>
{% else %}
	<h4>There are no jokes.</h4>
{% endif %}
{% endblock %}



{% block scripts %}
<script type="text/javascript">

	/* On page load. */
	$(document).ready(function() {
		$('#all_jokes_table').DataTable({
			"paging": false,
			"order": [[3, 'desc']],
			"searching": false,
			"info": false
		});
	});

	/* On clicking any of the stars on the page.
	 * Submit the updated rating to the server.
	 */
	$(document).off('click', '.star').on('click', '.star', function(e) {
		var $td = $(this).closest('td');
		var $spans = $td.find('.star');
		var $clickedStar = $(this);
		$spans.removeClass('checked');
		var rating = 0;
		$spans.each(function() {
			var r = true;
			if ($clickedStar.is($(this))) {
				r = false; // break
			}
			$(this).addClass('checked');
			rating++;
			return r;
		});

		var url = "{% url 'stats:update_rating' %}";
		var post_data = {
			'rating': rating,
			'joke_id': $td.closest('tr').attr('id'),
			'csrfmiddlewaretoken': '{{ csrf_token }}'
		}

		$.post(url, post_data);
	});

</script>
{% endblock %}



{% block styles %}
<style>
	
	table#all_jokes_table: {
		/*table-layout: fixed;*/
		width: 100%;
	}

	.joke-text {
		overflow: hidden;
		white-space: nowrap;
		text-overflow: ellipsis;
	}

	.centered-text {
		text-align: center;
	}

	.checked {
	    color: orange;
	}

	div.dataTables_paginate {
		text-align: center;
	}

	div.dataTables_paginate > a,
	div.dataTables_paginate > span > a {
		margin: 1em;
	}

	a.paginate_button.current {
		color: red;
	}
</style>
{% endblock %}

jokerank/templates/jokerank/login.html
{% extends 'jokerank/base.html' %}

{% block login-nav %}class="active"{% endblock%}

{% block content %}
<h2>Login (or <a href="{% url 'signup' %}">Signup</a>)</h2>
<hr>
<form id="login_form" method="POST" action="{% url 'login' %}">
    {% for field in form %}
    <div class="form-group">
        <label>{{ field.label|title }}</label>
        {{ field }}
    </div>
    {% endfor %}
    <button type="submit" class="btn">Login</button>
	{% csrf_token %}
</form>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
    $(document).ready(function() {
        $('#login_form').find('input').addClass('form-control');
    });
</script>
{% endblock %}

jokerank/templates/jokerank/logout-success.html
{% extends 'jokerank/base.html' %}


{% block content %}
	<h2>Thanks for visiting JokeDB.</h2>
{% endblock %}

jokerank/templates/jokerank/no-jokes-available.html
{% extends 'jokerank/base.html' %}

{% block content %}
	<h4>You rated all the available jokes. Thanks!</h4>
{% endblock %}